name: Main

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: yarn test
